version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: ecommerce_db
    environment:
      MYSQL_ROOT_PASSWORD: Haifa319*
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../database:/app/database  # Mount the database module

  customers:
    build:
      context: ./customers
    container_name: customers_service
    ports:
      - "5001:5001"
    depends_on:
      - db

  inventory:
    build:
      context: ./inventory
    container_name: inventory_service
    ports:
      - "5002:5002"
    depends_on:
      - db

  reviews:
    build:
      context: ./reviews
    container_name: reviews_service
    ports:
      - "5004:5004"
    depends_on:
      - db

  sales:
    build:
      context: ./sales
    container_name: sales_service
    ports:
      - "5003:5003"
    depends_on:
      - db

volumes:
  db_data:
